In [ ]:
# to install numpy
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
# to import numpy
import numpy as np 
# here np is an alias

In [3]:
# checking the version
np.__version__

'1.22.4'

In [4]:
# creating first array object 
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [5]:
# let us check the type of above 
print(type(a))

<class 'numpy.ndarray'>


In [6]:
# It is an object of class numpy.ndarray

In [9]:
# similarly we can create two dimensional array object
a = np.array([[1,2],[3,4]])
print(a)
print(type(a))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [10]:
# we can use ndmin as argument in case of np.array to give the minimum dimension to the object
a = np.array([i for i in range(1,11)],ndmin = 2)
print(a)
# Here above I have used list comprehension 

[[ 1  2  3  4  5  6  7  8  9 10]]


In [12]:
# we can also provide the datatype for the object

a = np.array([x for x in range(1,11)],ndmin = 1,dtype  = complex)
print(a)

[ 1.+0.j  2.+0.j  3.+0.j  4.+0.j  5.+0.j  6.+0.j  7.+0.j  8.+0.j  9.+0.j
 10.+0.j]


In [15]:
# Datatypes in numpy : We have  a large collection of datatypes in numpy
# strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
# integer - used to represent integer numbers. e.g. -1, -2, -3
# float - used to represent real numbers. e.g. 1.2, 42.42
# boolean - used to represent True or False.
# complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [ ]:
# A dtype object is constructed using the following syntax: 
# np.dtype(object,align,copy)

In [17]:
dt = np.dtype(np.int32)
print(dt)
# i1 , i2,i3 ,i4 are int8, int16,int
32

int32


32

In [18]:
dt = np.dtype('i4')
print(dt)

int32


In [19]:
# let us see the shape of ndarray

In [21]:
a = np.array([[i for i in range(1,6)],[i for i in range(6,11)]])
print(a)
print("Shape is ",a.shape)
# 2 rows 5 cols

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
Shape is  (2, 5)


In [22]:
# we can change the shape
a.shape = (5,2)
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [23]:
# similarly we have reshape function
b = a.reshape(2,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [24]:
# to create list in a range 
a = np.arange(30)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [25]:
print(a.ndim)

1


In [26]:
# let us reshape this :
b = a.reshape(2,5,3)

In [27]:
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [28]:
print(b.shape)

(2, 5, 3)


In [29]:
# to check item size(in bytes)
a = np.array([1,2,3,4],dtype = np.bool)

<ipython-input-29-87674af38ec1>:2: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  a = np.array([1,2,3,4],dtype = np.bool)


In [30]:
print(a.itemsize)

1


In [32]:
a = np.array([1,2,3,4],dtype = np.float32)
print(a.itemsize)

4


In [33]:
# There are different flags in numpy


In [35]:
x = np.array([i for i in range(1,10)])

In [36]:
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False



In [38]:
# let us create an empty array
x = np.empty([3,2],dtype = int)
print(x)

[[49060400        0]
 [       0        0]
 [       0        0]]


In [39]:
# let us now create an array with all zeros
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [40]:
# default dtype =  float
# we can change that also
x = np.zeros(10,dtype =int)

In [41]:
print(x)

[0 0 0 0 0 0 0 0 0 0]


In [42]:
print(np.zeros((5,5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [46]:
# similarly we can create ones 
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [47]:
# let us convert list to ndarray
var = [i for i in range(1,20)]
abc =  np.asarray(var)
print(abc)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [48]:
# similarly we can convert tuple in nd array
a = (1,2,3,4)
b = np.asarray(a)
print(b)

[1 2 3 4]


In [54]:
# Let us see arange and set start and end parameters
x = np.arange(10,20,4)
print(x)

[10 14 18]


In [55]:
print(np.linspace(1,20))

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]
